name: SSH

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Taipei
    container:
      image: pexcn/docker-images:bookworm-android

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fix run ssh2actions
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          sudo apt-get clean
          mkdir ~/.ssh && touch ~/.ssh/id_rsa

      #- name: Start SSH via tmate
      #  uses: P3TERX/ssh2actions@main

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
